name: Deploy Quart Themes preview to GitHub Pages
 
on:
  workflow_dispatch:
  schedule:
    - cron: "40 */4 * * *"
  push:
    branches:
      - v4
 
permissions:
  contents: write
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: true
 
jobs:
  build:
    if: ${{ github.repository != 'quartz-themes/quartz-themes-preview-template' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Update Quartz
        run: |
          git config pull.rebase >&- || git config pull.rebase false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config remote.template.url >&- || git remote add template https://github.com/quartz-themes/quartz-themes-preview-template.git
          git pull -X theirs template v4 --allow-unrelated-histories --no-edit
          git push
      - name: Install Dependencies
        uses: nick-fields/retry@v3
        with:
          command: npm ci
          timeout_minutes: 10
          max_attempts: 3
      - name: Fetch Quartz Theme
        uses: nick-fields/retry@v3
        with:
          command: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- ${{ github.event.repository.name }}
          timeout_minutes: 10
          max_attempts: 3
      - name: Build Quartz Docs
        uses: nick-fields/retry@v3
        with:
          command: npx quartz build -d docs
          timeout_minutes: 10
          max_attempts: 3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
