name: Deploy Quartz site to GitHub Pages
 
on:
  workflow_dispatch:
  schedule:
    - cron: "45 */1 * * *"
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Update Quartz (template)
        if: ${{ github.event.repository.name }} == "quartz-themes-preview-template"
        run: |
          git config pull.rebase false
          git remote add upstream https://github.com/jackyzha0/quartz.git
          git pull upstream v4
      - name: Update Quartz (preview)
        if: ${{ github.event.repository.name }} != "quartz-themes-preview-template"
        run: |
          git config pull.rebase false
          git remote add upstream https://https://github.com/quartz-themes/quartz-themes-preview-template.git
          git pull upstream v4
      - name: Push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_fetch: true
          skip_dirty_check: false
          commit_message: "[ci] flakes: auto-updated"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
      - name: Install Dependencies
        run: npm ci
      - name: Fetch Quartz Theme
        if: ${{ github.event.repository.name }} != "quartz-themes-preview-template"
        run: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- ${{ github.event.repository.name }}
      - name: Build Quartz Docs
        run: npx quartz build -d docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
